### ISSUE TITLE
Tweet atmıyor.

### ISSUE THREAD

**Issue by cnhsn** [BatuhanK/TurkceCanavari#4]
Uygulama sunucu tarafında sıkıntısız çalışıyor fakat insanlara mention atıp tweet atmıyor. Çünkü hesabı oluşturduğum uygulamaya sokamıyorum.

**Comment by BatuhanK** [comment]
Selam, https://github.com/BatuhanK/TurkceCanavari/blob/master/tweets.js#L68-L69 surada yazdigi gibi suan her 256 tweetten 1 tanesine yanit veriyor

**Comment by cnhsn** [comment]
Peki bu sayıyı düşürmem bi sorun yol açar mı? Rn az kaça düşürmeliyim?

**Comment by BatuhanK** [comment]
Izlediginiz keywordlere, atacaginiz tweet sayisina, tweet icerigine gore, hesabinizin alacagi etkilesime gore degisir. Bunu net olarak bilmek mumkun degil, iyi calismalar
